### ISSUE TITLE
Command /heydj-whats-on-air fails

### ISSUE THREAD

**Issue by g-six** [nerubia/dj-iron-issues#15]
**Describe the bug**
When calling the /heydj-whats-on-air command and there are more than 100 tracks queued.

**To Reproduce**
1. Make sure there are more than 100 tracks queued away from the current playing track.
2. Enter slash command '/heydj-whats-on-air'
3. Error:
   On Slack:  
      Darn - that slash command didn't work (error message: `Timeout was reached`). Manage the command at DJ Iron.  
   Logs:  
      ```
    Error: Request failed with status code 429
    at createError (/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/node_modules/axios/lib/adapters/http.js:201:11)
    at emitNone (events.js:111:20)  
    
   url:  
   https://api.spotify.com/v1/users/ruby-robin/playlists/6bYTOCnMdARhHks9NOUD1A?offset=100&limit=100

      ```

**Expected behavior**
This should return 11 tracks starting from the current playing track and ending in the last track in the queue.

**Screenshots**
Error after entering slash command
![image](https://user-images.githubusercontent.com/603961/43621066-27bd1374-9708-11e8-8dca-6187dfb804d7.png)

**Timeline:**
 - Day: Today
 - Time: around 10:00AM

**Comment by dobidobz** [comment]
**Related bug:** the "last" track is showing same value with the "current" track.

as checked in the actual playlist, it is also not a duplicate track.
the last track should have been _153. Nobody Can Drag Me Down - Paul Laone_

![screen shot 2018-08-03 at 11 56 41 am](https://user-images.githubusercontent.com/4723863/43623550-6d44aefa-9714-11e8-81d7-7558cb539dc1.png) ![screen shot 2018-08-03 at 11 56 24 am](https://user-images.githubusercontent.com/4723863/43623551-6d8382d8-9714-11e8-9653-dc8537cceeca.png)
