### ISSUE TITLE
Update /state - add fields

### ISSUE THREAD

**Issue by jarielbalberona** [nerubia/dj-iron-issues#27]
**Update /state**

Add "Someone is on call" field.
-Useful when the current volume is too low.
Add total tracks/position of the last added track.
Add thumbnail of the currently playing track.

On call - Paused.
<img width="641" alt="screen shot 2018-09-18 at 1 04 50 pm" src="https://user-images.githubusercontent.com/11960968/45665443-8d24c400-bb43-11e8-8b85-47349871fafe.png">
On call - Playing
<img width="644" alt="screen shot 2018-09-18 at 1 05 05 pm" src="https://user-images.githubusercontent.com/11960968/45665444-8d24c400-bb43-11e8-98ab-8083168ae479.png">

No one is on call - Playing.

<img width="647" alt="screen shot 2018-09-18 at 1 05 19 pm" src="https://user-images.githubusercontent.com/11960968/45665445-8dbd5a80-bb43-11e8-9121-1c9ccf4216d3.png">

Speaker icon indicates the state of the player.

**Slack Message Builder**
[View](https://api.slack.com/docs/messages/builder?msg=%7B%22username%22%3A%22DJ%20Iron%22%2C%22attachments%22%3A%5B%7B%22color%22%3A%22%2336a64f%22%2C%22title%22%3A%22111.%20Masaya%20Ako%20Sayo%20(feat.%20Ms.%20Yumi)%22%2C%22text%22%3A%22Curse%20One%2C%20Yumi%22%2C%22fields%22%3A%5B%7B%22title%22%3A%22Total%22%2C%22value%22%3A%22185%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Volume%22%2C%22value%22%3A%22%3Aloud_sound%3A%2015%25%22%2C%22short%22%3Atrue%7D%5D%2C%22author_name%22%3A%22%3Abulb%3A%20Someone%20is%20on%20call%22%2C%22footer%22%3A%22Playling%20DJ%20Iron%20playlist%20from%20Hallway%22%2C%22thumb_url%22%3A%22https%3A%2F%2Fi.scdn.co%2Fimage%2F966ade7a8c43b72faa53822b74a899c675aaafee%22%7D%5D%7D)

**_Open for additional suggestions._**
Open the builder, edit and paste the link or screenshot here.

**Comment by g-six** [comment]
Suggestion: shorten the body

[Slack Message Builder](https://api.slack.com/docs/messages/builder?msg=%7B%22username%22%3A%22DJ%20Iron%22%2C%22attachments%22%3A%5B%7B%22color%22%3A%22%2336a64f%22%2C%22title%22%3A%22111.%20Masaya%20Ako%20Sayo%20(feat.%20Ms.%20Yumi)%22%2C%22text%22%3A%22Curse%20One%2C%20Yumi%22%2C%22fields%22%3A%5B%7B%22title%22%3A%22Device%22%2C%22value%22%3A%22Hallway%22%2C%22short%22%3Atrue%7D%2C%7B%22title%22%3A%22Volume%20%2F%20State%22%2C%22value%22%3A%2215%25%22%2C%22short%22%3Atrue%7D%5D%2C%22author_name%22%3A%22Someone%20on%20call%22%2C%22thumb_url%22%3A%22https%3A%2F%2Fi.scdn.co%2Fimage%2F966ade7a8c43b72faa53822b74a899c675aaafee%22%7D%5D%7D
)

![image](https://user-images.githubusercontent.com/603961/45612869-f7335f80-ba96-11e8-8860-a0c4003ef60e.png)

**Comment by jarielbalberona** [comment]
How about the track status, Playing/Paused?

Edit: nvm, saw it.

**Comment by jarielbalberona** [comment]
Issue updated.
