### ISSUE TITLE
Playlist should be visible to requester only (to avoid spam look in the channel).

### ISSUE THREAD

**Issue by mayjillalicaya** [nerubia/dj-iron-issues#3]
- If someone requests to view the playlist, result should only be visible to the requester.

**Comment by itsgem** [comment]
Can we also include the last song on the list and what time it will play?

**Comment by g-six** [comment]
@itsgem Something like a `...` in between the next few tracks plus the last track after the `...`?

**Comment by g-six** [comment]
Something like:
![image](https://user-images.githubusercontent.com/603961/43235682-23c27fa2-90b4-11e8-83a8-20aea2dd1690.png)

**Comment by g-six** [comment]
@itsgem can you file a separate issue?

**Comment by g-six** [comment]
https://github.com/nerubia/dj-iron/pull/7

**Comment by itsgem** [comment]
@g-six Filed: #13
