### ISSUE TITLE
Documentation: List of commands available

### ISSUE THREAD

**Issue by itsgem** [nerubia/dj-iron-issues#6]
Something like: https://getjukebot.com/#how-it-works

**Comment by dobidobz** [comment]
or may also provide `/heydj-help` command for the list of commands and common troubleshooting/notes

**Comment by g-six** [comment]
See our [dummy guide](https://share.nuclino.com/p/DJ-Iron-for-Dummies-9fOOvMlvIqcCRcrYAiyvuM) (WIP)

**Comment by g-six** [comment]
Update: added slash command for users to easily view the list of commands `/heydj`
