### ISSUE TITLE
Should we allow duplicate track requests?

### ISSUE THREAD

**Issue by g-six** [nerubia/dj-iron-issues#7]
![image](https://user-images.githubusercontent.com/603961/43234707-580f60a8-90b0-11e8-8089-62f5695c49e1.png)

The track *Supermarket Flowers* was added twice (No. 8 and No. 20)

**Comment by errosales** [comment]
Or maybe allow it only if the duplicate track was already played?

**Comment by g-six** [comment]
Discussed with @errosales the other day and due to the many issues that can be fixed if we disallow this, we have decided to not support this for now.
